//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_QLKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int booking_id { get; set; }
        public string customer_name { get; set; }
        public System.DateTime check_in_date { get; set; }
        public decimal total_amount { get; set; }
        public Nullable<decimal> deposit_amount { get; set; }
        public string payment_ref_id { get; set; }
        public string payment_status { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    }
}
