//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_QLKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDatPhong
    {
        public int ChiTietDatPhongId { get; set; }
        public int DatPhongId { get; set; }
        public Nullable<int> PhongId { get; set; }
        public Nullable<int> LoaiPhongId { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public int SoLuong { get; set; }
        public Nullable<System.DateTime> NgayDen { get; set; }
        public Nullable<System.DateTime> NgayDi { get; set; }
        public Nullable<decimal> GiamGia { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public byte TrangThaiPhong { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        public virtual DatPhong DatPhong { get; set; }
        public virtual LoaiPhong LoaiPhong { get; set; }
        public virtual Phong Phong { get; set; }
    }
}
