//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_QLKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGiaHinhAnh
    {
        public int HinhAnhId { get; set; }
        public int DanhGiaId { get; set; }
        public string DuongDanAnh { get; set; }
    
        public virtual DanhGia DanhGia { get; set; }
    }
}
