//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_QLKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DanhGia()
        {
            this.DanhGiaHinhAnhs = new HashSet<DanhGiaHinhAnh>();
        }
    
        public int DanhGiaId { get; set; }
        public int PhongId { get; set; }
        public int MaKhachHang { get; set; }
        public byte Diem { get; set; }
        public string BinhLuan { get; set; }
        public System.DateTime NgayTao { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual Phong Phong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGiaHinhAnh> DanhGiaHinhAnhs { get; set; }
    }
}
