//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_QLKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatPhong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DatPhong()
        {
            this.ChiTietDatDichVus = new HashSet<ChiTietDatDichVu>();
            this.ChiTietDatPhongs = new HashSet<ChiTietDatPhong>();
            this.HoaDons = new HashSet<HoaDon>();
            this.VNPAY_Transaction_Logs = new HashSet<VNPAY_Transaction_Logs>();
        }
    
        public int DatPhongId { get; set; }
        public string MaDatPhong { get; set; }
        public Nullable<int> MaKhachHang { get; set; }
        public Nullable<int> NhanVienId { get; set; }
        public System.DateTime NgayDat { get; set; }
        public Nullable<System.DateTime> NgayNhan { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public Nullable<int> SoDem { get; set; }
        public Nullable<int> SoLuongKhach { get; set; }
        public byte TrangThaiDatPhong { get; set; }
        public byte TrangThaiThanhToan { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<byte> HinhThucThanhToan { get; set; }
        public Nullable<int> MaKhuyenMai { get; set; }
        public string GhiChu { get; set; }
        public System.DateTime NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string PaymentRefId { get; set; }
        public string PaymentMethod { get; set; }
        public string OnlinePaymentStatus { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string CustomerName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDatDichVu> ChiTietDatDichVus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDatPhong> ChiTietDatPhongs { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual KhuyenMai KhuyenMai { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VNPAY_Transaction_Logs> VNPAY_Transaction_Logs { get; set; }
    }
}
