//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_QLKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DichVu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DichVu()
        {
            this.ChiTietDatDichVus = new HashSet<ChiTietDatDichVu>();
        }
    
        public int DichVuId { get; set; }
        public string MaDichVu { get; set; }
        public string TenDichVu { get; set; }
        public string MoTa { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public Nullable<decimal> GiaUuDai { get; set; }
        public bool DaHoatDong { get; set; }
        public System.DateTime NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> LoaiDichVuId { get; set; }
        public string Icon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDatDichVu> ChiTietDatDichVus { get; set; }
        public virtual LoaiDichVu LoaiDichVu { get; set; }
    }
}
