//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_QLKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaTheoNgay
    {
        public int GiaTheoNgayId { get; set; }
        public int PhongId { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
        public decimal GiaCoBan { get; set; }
        public string LoaiGia { get; set; }
        public Nullable<decimal> PhanTramGiam { get; set; }
        public string MoTa { get; set; }
        public bool DaHoatDong { get; set; }
        public System.DateTime NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        public virtual Phong Phong { get; set; }
    }
}
