//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_QLKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.ThanhToans = new HashSet<ThanhToan>();
        }
    
        public int HoaDonId { get; set; }
        public string MaHoaDon { get; set; }
        public Nullable<int> DatPhongId { get; set; }
        public Nullable<int> MaKhachHang { get; set; }
        public System.DateTime NgayLap { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<decimal> GiamGia { get; set; }
        public Nullable<decimal> Thue { get; set; }
        public Nullable<decimal> ThanhToanCuoi { get; set; }
        public byte TrangThaiHoaDon { get; set; }
        public string GhiChu { get; set; }
        public string PhuongThucThanhToan { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
        public string NguoiLapHoaDon { get; set; }
        public System.DateTime NgayTao { get; set; }
    
        public virtual DatPhong DatPhong { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThanhToan> ThanhToans { get; set; }
    }
}
