//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_QLKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhuyenMai
    {
        public int KhuyenMaiId { get; set; }
        public string MaKhuyenMai { get; set; }
        public string TenKhuyenMai { get; set; }
        public Nullable<byte> LoaiKhuyenMai { get; set; }
        public Nullable<decimal> GiaTri { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public string DieuKienApDung { get; set; }
        public Nullable<int> SoLanSuDungToiDa { get; set; }
        public bool DaHoatDong { get; set; }
    }
}
