//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_QLKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanCongCongViec
    {
        public int PhanCongId { get; set; }
        public string MaPhanCong { get; set; }
        public int PhongId { get; set; }
        public int NhanVienBuongPhongId { get; set; }
        public Nullable<int> NhanVienLeTanId { get; set; }
        public byte TrangThaiCongViec { get; set; }
        public byte MucDoUuTien { get; set; }
        public string GhiChu { get; set; }
        public string GhiChuNhanVien { get; set; }
        public System.DateTime ThoiGianPhanCong { get; set; }
        public Nullable<System.DateTime> ThoiGianBatDau { get; set; }
        public Nullable<System.DateTime> ThoiGianHoanThanh { get; set; }
        public Nullable<System.DateTime> ThoiGianDuKien { get; set; }
        public System.DateTime NgayTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual NhanVien NhanVien1 { get; set; }
        public virtual Phong Phong { get; set; }
    }
}
