//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_QLKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhongAnh
    {
        public int PhongAnhId { get; set; }
        public int PhongId { get; set; }
        public string Url { get; set; }
        public string ChuThich { get; set; }
        public int ThuTu { get; set; }
        public System.DateTime NgayTao { get; set; }
    
        public virtual Phong Phong { get; set; }
    }
}
