//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_QLKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiKhoan()
        {
            this.TokenLogins = new HashSet<TokenLogin>();
        }
    
        public int TaiKhoanId { get; set; }
        public string TenDangNhap { get; set; }
        public string MatKhauHash { get; set; }
        public byte LoaiTaiKhoan { get; set; }
        public Nullable<int> MaKhachHang { get; set; }
        public bool DaKichHoat { get; set; }
        public System.DateTime NgayTao { get; set; }
        public string OTPCode { get; set; }
        public Nullable<System.DateTime> OTPExpires { get; set; }
        public string Email { get; set; }
        public Nullable<int> MaNhanVien { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TokenLogin> TokenLogins { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
