//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_QLKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhToan
    {
        public int ThanhToanId { get; set; }
        public int HoaDonId { get; set; }
        public System.DateTime NgayThanhToan { get; set; }
        public decimal SoTien { get; set; }
        public Nullable<byte> PhuongThucThanhToan { get; set; }
        public string MaGiaoDich { get; set; }
        public byte TrangThaiThanhToan { get; set; }
        public string GhiChu { get; set; }
        public string NguoiThucHien { get; set; }
        public string HinhAnhBienLai { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
    }
}
