//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_QLKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TokenLogin
    {
        public int TokenId { get; set; }
        public int MaTaiKhoan { get; set; }
        public System.DateTime NgayTao { get; set; }
        public System.DateTime NgayHetHan { get; set; }
        public string token { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
