//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_QLKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VNPAY_Transaction_Logs
    {
        public int log_id { get; set; }
        public string booking_ref_id { get; set; }
        public string vnp_txn_ref { get; set; }
        public decimal vnp_amount { get; set; }
        public string vnp_response_code { get; set; }
        public string vnp_transaction_status { get; set; }
        public string log_details { get; set; }
        public Nullable<System.DateTime> log_time { get; set; }
    }
}
